In [40]:
import numpy as np
import pandas as pd

df = pd.read_csv('executive.dandrois', sep='\t',header=None)
df.columns=['patient ID', 'time', 'condition1', 'scan-in-condition1', 'condition2', 'condition3', 'ignore', 'brain','nan']
df=df.drop(columns=['nan'])
df.head()

,patient ID,time,condition1,scan-in-condition1,condition2,condition3,ignore,brain
0,1501,1,1,1,5,3,-999,10011.6
1,1501,2,1,2,5,3,-999,10011.6
2,1501,3,1,3,5,3,-999,10011.6
3,1501,4,1,4,5,3,-999,10011.6
4,1501,5,1,5,5,3,-999,10012.0

In [41]:
df.head()

,patient ID,time,condition1,scan-in-condition1,condition2,condition3,ignore,brain
0,1501,1,1,1,5,3,-999,10011.6
1,1501,2,1,2,5,3,-999,10011.6
2,1501,3,1,3,5,3,-999,10011.6
3,1501,4,1,4,5,3,-999,10011.6
4,1501,5,1,5,5,3,-999,10012.0

In [42]:
# first grab data that is executive rest for controls
exec_rest_controls = df.loc[(df['patient ID'] < 3000) & (df['patient ID'] >= 2000) & (df['condition2']== 5)]
exec_rest_controls.head()

,patient ID,time,condition1,scan-in-condition1,condition2,condition3,ignore,brain
270,2301,1,1,1,5,3,-999,10025.00
271,2301,2,1,2,5,3,-999,10025.00
272,2301,3,1,3,5,3,-999,10025.00
273,2301,4,1,4,5,3,-999,10025.00
274,2301,5,1,5,5,3,-999,9990.18

In [43]:
exec_rest_controls.to_csv('executive_rest_controls.csv')

In [44]:
# Interoceptive resting data for control population

df = pd.read_csv('interoceptive_forward.dandrois', sep='\t',header=None)
df.columns=['patient ID', 'time', 'condition1', 'scan-in-condition1', 'condition2', 'condition3', 'ignore', 'brain','nan']
df=df.drop(columns=['nan'])
interoceptive_rest_controls = df.loc[(df['patient ID'] < 3000) & (df['patient ID'] >= 2000) & (df['condition2']== 5)]
interoceptive_rest_controls.head()

,patient ID,time,condition1,scan-in-condition1,condition2,condition3,ignore,brain
270,2301,1,1,1,5,3,-999,10002.30
271,2301,2,1,2,5,3,-999,10002.30
272,2301,3,1,3,5,3,-999,10002.30
273,2301,4,1,4,5,3,-999,10002.30
274,2301,5,1,5,5,3,-999,9976.01

In [45]:
interoceptive_rest_controls.to_csv('interoceptive_rest_controls.csv')

In [46]:
# Salience resting data for control population
df = pd.read_csv('salience_forward.dandrois', sep='\t',header=None)
df.columns=['patient ID', 'time', 'condition1', 'scan-in-condition1', 'condition2', 'condition3', 'ignore', 'brain','nan']
df=df.drop(columns=['nan'])
salience_rest_controls = df.loc[(df['patient ID'] < 3000) & (df['patient ID'] >= 2000) & (df['condition2']== 5)]
salience_rest_controls.head()

,patient ID,time,condition1,scan-in-condition1,condition2,condition3,ignore,brain
270,2301,1,1,1,5,3,-999,10017.60
271,2301,2,1,2,5,3,-999,10017.60
272,2301,3,1,3,5,3,-999,10017.60
273,2301,4,1,4,5,3,-999,10017.60
274,2301,5,1,5,5,3,-999,9986.47

In [47]:
salience_rest_controls.to_csv('salience_rest_controls.csv')